name: Create Draft Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: self-hosted
    steps:
      - name: Get tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: "Release ${{ env.TAG_NAME }}"
          body: "This is an automated draft release for tag ${{ env.TAG_NAME }}"
          draft: true
          prerelease: false
